version: "3.9"

services:
  web:
    build: .
    command: gunicorn cars_project.wsgi:application --bind 0.0.0.0:8000 --workers 4 #python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"